END,ERROR,FNAME,FULL_FNAME,PARENT_END,PARENT_RUNTIME,PARENT_START,RATE,ROWS,RUNTIME,SRC_COUNT,START,STATUS,WARNING
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,BREADERS.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\BREADERS.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,4,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'OR'. (156) (SQLExecDirectW) ),CERTICATION OR DIPLOMATE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\CERTICATION OR DIPLOMATE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42S02'   [42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'dbo.CERTIFICATION'. (208) (SQLExecDirectW) ),CERTIFICATION LIST.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\CERTIFICATION LIST.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'TABLE'. (156) (SQLExecDirectW) ),DEP ADDRESS TABLE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\DEP ADDRESS TABLE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'TABLE_OLD'. (102) (SQLExecDirectW) ),DEP ADDRESS TABLE_OLD.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\DEP ADDRESS TABLE_OLD.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'TABLE'. (156) (SQLExecDirectW) ),DISTRICT ADDRESS TABLE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\DISTRICT ADDRESS TABLE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,,DTPROPERTIES.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\DTPROPERTIES.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,,empty table
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'INDEX'. If this is intended as a part of a table hint  A WITH keyword and parenthesis are now required. See SQL Server Books Online for proper syntax. (1018) (SQLExecDirectW) ),FORM LETTERS.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\FORM LETTERS.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW) ),INSURANCE - COMMERCIAL LIABILITY.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\INSURANCE - COMMERCIAL LIABILITY.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '-'. (102) (SQLExecDirectW) ),INSURANCE - MEDICAL LIABILITY.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\INSURANCE - MEDICAL LIABILITY.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,LICENSE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\LICENSE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,1735,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,LICENSE TYPE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\LICENSE TYPE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,1735,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42S02'   [42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'dbo.MAILING'. (208) (SQLExecDirectW) ),MAILING LIST.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\MAILING LIST.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'INFORMATION'. (102) (SQLExecDirectW) ),MEDICAL SPECIALITY INFORMATION.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\MEDICAL SPECIALITY INFORMATION.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'LIST'. (102) (SQLExecDirectW) ),MEDICAL SPECIALITY LIST.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\MEDICAL SPECIALITY LIST.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'PRIMARY'. (156) (SQLExecDirectW) ),MEMBERS.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\MEMBERS.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,MSCHANGE_TRACKING_HISTORY.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\MSCHANGE_TRACKING_HISTORY.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,1916,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'CODE'. (102) (SQLExecDirectW) ),NEW ZIP CODE TABLE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\NEW ZIP CODE TABLE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,,OTHER_LANGUAGES.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\OTHER_LANGUAGES.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,,empty table
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42S02'   [42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'dbo.PROFESSIONAL'. (208) (SQLExecDirectW) ),PROFESSIONAL TITLE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\PROFESSIONAL TITLE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'HISTORY'. (102) (SQLExecDirectW) ),PROVIDER CME HISTORY.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\PROVIDER CME HISTORY.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'INFORMATION'. (102) (SQLExecDirectW) ),PROVIDER SPECIALTY INFORMATION.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\PROVIDER SPECIALTY INFORMATION.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'TBL'. (102) (SQLExecDirectW) ),SERVICE OFFICE TBL.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\SERVICE OFFICE TBL.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'OFF'. (156) (SQLExecDirectW) ),SIGN OFF SHEET.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\SIGN OFF SHEET.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,SIGNOFFSHEET_TMP.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\SIGNOFFSHEET_TMP.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,1393,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'AND'. (156) (SQLExecDirectW) ),STATES  AND ABBREVIATIONS TABLE.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\STATES  AND ABBREVIATIONS TABLE.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,SYSDIAGRAMS.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\SYSDIAGRAMS.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,3,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42S02'   [42S02] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'dbo.TELEPHONE'. (208) (SQLExecDirectW) ),TELEPHONE LIST.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\TELEPHONE LIST.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,USERPERMISSION.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\USERPERMISSION.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,12,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 357  in dump_table    gotddl=write_ddl_info(args fname table row_gen)  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 278  in write_ddl_info    inf.write_csv(ddl_file ddl_rows log=args.log  clean = args.clean)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 348  in write_csv    fname = clean_name(fname)  File  e: Release_UAT bwcroot mainframe2 bwclib inf.py   line 489  in clean_name    word = ''.join(map(keepchar astr ))TypeError: 'WindowsPath' object is not iterable,USZIPCODELIST.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\USZIPCODELIST.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,29596,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'SENT'. (102) (SQLExecDirectW) ),VERIFY LETTERS SENT.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\VERIFY LETTERS SENT.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
,ERROR:######  Traceback (most recent call last):  File  e: Release_UAT bwcroot mainframe2 bwcrun run_extract.py   line 347  in dump_table    src_count=list(args.con.fetchdict(count_sql size=1))[0]['COUNT']  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 185  in fetchdict    self.exe(sql)  File  e: Release_UAT bwcroot mainframe2 bwclib dblib.py   line 214  in exe    self.cursor.execute(sql)pyodbc.ProgrammingError: ('42000'   [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near the keyword 'KEY'. (156) (SQLExecDirectW) ),YES_OR_NO.csv.gz,E:\EXTRACTS\a75551\EL\uat\sql_etl_dep\DEP\dbo\data\2023_02_02PM\extracts\YES_OR_NO.csv.gz,20230202-13:05:49,2.6,20230202-13:05:46,0,0,0,0,,error,
